### ISSUE TITLE
License

### ISSUE THREAD

**Issue by luisdebastos** [zetamatta/PathToClip#2]
Hi guys,

No issue per se. The License section is undefined, just wondering if it will be considered as free/public. Just trying to identify the license on this useful tool and confirm if I can use it at work, based on the license defined for it. 

Regards.

**Comment by hymkor** [comment]
Thank you.
I Read this issue and  I create the LICENSE file by MIT-LICENSE.

Please use it freely.

**Comment by luisdebastos** [comment]
Excellent, thank you so much!
